import socket

# Server details
server_address = 'izani.synology.me'
server_port = 8443

try:
    # Create a socket object
    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    # Connect to the server
    client_socket.connect((server_address, server_port))

    # Prompt user for Student ID
    student_id = input("Enter your Student ID: ")

    # Send Student ID to the server
    client_socket.sendall(student_id.encode())

    # Receive and read the server response (the unique URL)
    url = client_socket.recv(1024).decode()

    # Display the unique URL to the user
    print("Unique URL generated by the server:", url)

    # Close the connection
    client_socket.close()

except ConnectionRefusedError:
    print("Connection refused. Make sure the server is running and accessible.")
except Exception as e:
    print("An error occurred:", str(e))

